marakana-training/src/main/java/com/marakana/contacts/entities/Company.java
package com.marakana.contacts.entities;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

@Entity
public class Company extends Contact {

	@OneToMany(mappedBy = "company", cascade = CascadeType.ALL, orphanRemoval = true)
	private Set<Office> offices;

	public Company() {
	}

	public Company(String name, Set<Office> offices) {
		super(name);
		this.offices = offices;
	}

	public Set<Office> getOffices() {
		return offices;
	}

	public void setOffices(Set<Office> offices) {
		this.offices = offices;
	}

}

marakana-training/src/main/java/com/marakana/contacts/entities/UrlEntity.java
package com.marakana.contacts.entities;

import javax.persistence.MappedSuperclass;

@MappedSuperclass
public class UrlEntity extends BaseEntity {

	public String getUrl() {
		return getClass().getSimpleName().toLowerCase() + "?id=" + getId();
	}

}

marakana-training/src/main/java/com/marakana/contacts/controllers/CompanyController.java
package com.marakana.contacts.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.marakana.contacts.entities.Company;
import com.marakana.contacts.repositories.CompanyRepository;

@Controller
public class CompanyController {

	@Autowired
	private CompanyRepository companyRepository;

	@RequestMapping(value = "/company", params = "add", method = RequestMethod.GET)
	public String getAddCompany() {
		return "company/add";
	}

	@RequestMapping(value = "/company", params = "edit", method = RequestMethod.GET)
	public String getEditCompany(@RequestParam long id, Model model) {
		model.addAttribute("company", companyRepository.findOne(id));
		return "company/edit";
	}

	@RequestMapping(value = "/company", method = RequestMethod.GET)
	public String getViewCompany(@RequestParam long id, Model model) {
		model.addAttribute("company", companyRepository.findOne(id));
		return "company/view";
	}

	@RequestMapping(value = "/company", params = "add", method = RequestMethod.POST)
	public String postAddCompany(@RequestParam String name) {
		Company company = new Company(name, null);
		company = companyRepository.save(company);

		return "redirect:company?id=" + company.getId();
	}

	@RequestMapping(value = "/company", params = "edit", method = RequestMethod.POST)
	public String postEditCompany(@RequestParam long id,
			@RequestParam String name) {
		Company company = companyRepository.findOne(id);
		company.setName(name);
		companyRepository.save(company);

		return "redirect:company?id=" + company.getId();
	}

	@RequestMapping(value = "/company", params = "delete", method = RequestMethod.POST)
	public String postDeleteCompany(@RequestParam long id) {
		companyRepository.delete(id);
		return "redirect:contacts";
	}

}

marakana-training/src/main/webapp/view/company/add.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>add company</title>
</head>
<body>
	<h1>add company</h1>
	<form action="company" method="post">
	<input type="hidden" name="add">
	<ul>
		<li>name: <input type="text" name="name"></li>
	</ul>
	<input type="submit" value="add">
	</form>
	<a href="contacts">back to contact list</a>
</body>
</html>

marakana-training/src/main/webapp/view/company/edit.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>edit company</title>
</head>
<body>
	<h1>edit company</h1>
	<form action="company" method="post">
	<input type="hidden" name="edit">
	<input type="hidden" name="id" value="${company.id}">
	<ul>
		<li>name: <input type="text" name="name" value="${company.name}"></li>
	</ul>
	<input type="submit" value="edit">
	</form>
	<form action="company" method="post">
	<input type="hidden" name="delete">
	<input type="hidden" name="id" value="${company.id}">
	<input type="submit" value="delete">
	</form>
	<a href="contacts">back to contact list</a>
</body>
</html>

marakana-training/src/main/webapp/view/company/view.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>${company.name}</title>
</head>
<body>
	<h1>${company.name}</h1>
	<ul>
		<c:forEach var="office" items="${company.offices}">
			<li><a href="${office.url}">${office.name}</a></li>
		</c:forEach>
	</ul>
	<a href="${company.url}&edit">edit company</a> |
	<a href="office?add&company_id=${company.id}">add office</a> |
	<a href="contacts">back to contact list</a>
</body>
</html>